#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:mysql://212.64.78.189:3306/ichat?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: syf@1999
#    max-idle: 10
#    max-wait: 10000
#    min-idle: 5
#    initial-size: 5
#    validation-query: SELECT 1
#    test-on-borrrow: false
#    test-while-idle: true
#    time-between-eviction-runs-millis: 18800
#
## 配置https
#https:
#  port: 8443
#  key-store: classpath:keystore.jks
#  key-store-password: kurento
#  key-store-type: JKS
#  key-alias: kurento-selfsigned
